version: "3.9"
services:

  backend:
    image: sudohackin/hr-backend:1.0.8
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hr
      SPRING_DATASOURCE_USERNAME: "hr-hackaton"
      SPRING_DATASOURCE_PASSWORD: "hr-hackaton-pass"
    ports:
      - "8060:9090"
  resume-searcher:
    image: sudohackin/hr-resume-parser:latest
    ports:
      - "8090:5000"
  vacancy-searcher:
    image: sudohackin/hr-vacancy-parser:1.0.1
    ports:
      - "8070:5000"
  company-searcher:
    image: sudohackin/hr-company-parser:latest
    ports:
      - "8080:5000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "hr"
      POSTGRES_USER: "hr-hackaton"
      POSTGRES_PASSWORD: "hr-hackaton-pass"
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "hr-hackaton@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "hr-hackaton-pass"
    ports:
      - "5050:80"
  bot:
    container_name: bot_container
    build: telegram-bot
    environment:
      BACKEND_PATH: "http://127.0.0.1:8060"
      SUGGEST_PATH: "http://127.0.0.1:8080/suggest"
      LOGGING_LEVEL: "INFO"
volumes:
  database_data:
  db:
