server:
  port: 9090
spring:
  #  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: hr-hackaton
    password: hr-hackaton-pass
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
#logging:
#  level:
#    org.apache.*: debug